# Generated by Django 2.1.7 on 2019-03-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('bedrooms', models.IntegerField()),
                ('hallkichen', models.IntegerField()),
                ('area_sqft', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
            ],
        ),
    ]
