# Generated by Django 2.1.7 on 2019-04-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20190409_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('bath', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('area_sqft', models.FloatField()),
                ('area_type', models.CharField(max_length=100)),
                ('hk', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advs', to='broker.Profile')),
            ],
        ),
    ]
